### ISSUE TITLE
  RuntimeException PHP 8.2.13 LARAVEL 10.38.1 Failed to send an update.

### ISSUE THREAD

**Issue by hen3b182** [benbjurstrom/livewire-mercure-demo#1]
```
Route::get('/test', function () {

    $type = request()->input('type', 'Public'); // Default to 'Public'



        if ($type === 'Private') {

            $userId = request()->input('user_id', '1'); // Default user ID

            $message = request()->input('private_message', 'I have a secret to tell you!');



            broadcast(new NewPrivateMessage($message, $userId));



            return response()->json(['message' => 'Private message was sent!']);

        }



        $message = request()->input('public_message', 'Hello everyone!');

            broadcast(new NewMessage($message));



        return response()->json(['message' => 'Public message was sent!']);



});
```

my docker-compose.yml (running without sail)

```
services:
    laravel.test:
        build:
            context: ./vendor/laravel/sail/runtimes/8.2
            dockerfile: Dockerfile
            args:
                WWWGROUP: '1000'
        image: sail-8.2/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '1000'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - mysql
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'sail-mysql:/var/lib/mysql'
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
    mercure:
        image: dunglas/mercure
        restart: unless-stopped
        environment:
            # Uncomment the following line to disable HTTPS
            SERVER_NAME: ':80'
            MERCURE_PUBLISHER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
            MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
            MERCURE_EXTRA_DIRECTIVES: |
                cors_origins http://localhost
                ui
                subscriptions
        # Uncomment the following line to enable the development mode
        command: /usr/bin/caddy run --config /etc/caddy/Caddyfile.dev
        ports:
            - '8888:80'
            - '4433:443'
        volumes:
            - mercure_data:/data
            - mercure_config:/config
networks:
    sail:
        driver: bridge
volumes:
    mercure_data:
    mercure_config:
    sail-mysql:
        driver: local


```

console:
```
PS \livewire-mercure-demo> docker compose up
time="2023-12-21T16:54:40+01:00" level=warning msg="The \"PWD\" variable is not set. Defaulting to a blank string."
[+] Running 3/3
 ✔ Container livewire-mercure-demo-mysql-1         Created                                                                                    0.0s
 ✔ Container livewire-mercure-demo-mercure-1       Recreated                                                                                  0.1s
 ✔ Container livewire-mercure-demo-laravel.test-1  Created                                                                                    0.0s
Attaching to laravel.test-1, mercure-1, mysql-1
mysql-1         | [Entrypoint] MySQL Docker Image 8.0.32-1.2.11-server
mercure-1       | {"level":"info","ts":1703174081.6410258,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile.dev","config_adapter":""}
mercure-1       | {"level":"warn","ts":1703174081.6424212,"msg":"Caddyfile input is not formatted; run 'caddy fmt --overwrite' to fix inconsistencies","adapter":"caddyfile","file":"/etc/caddy/Caddyfile.dev","line":3}
mercure-1       | {"level":"info","ts":1703174081.6441708,"logger":"admin","msg":"admin endpoint started","address":"localhost:2019","enforce_origin":false,"origins":["//localhost:2019","//[::1]:2019","//127.0.0.1:2019"]}
mercure-1       | {"level":"warn","ts":1703174081.6443107,"logger":"http.auto_https","msg":"server is listening only on the HTTP port, so no automatic HTTPS will be applied to this server","server_name":"srv0","http_port":80}
mercure-1       | {"level":"info","ts":1703174081.6448932,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0xc00029bb00"}
mercure-1       | {"level":"info","ts":1703174081.6449819,"logger":"http.log","msg":"server running","name":"srv0","protocols":["h1","h2","h3"]}
mercure-1       | {"level":"info","ts":1703174081.64524,"msg":"autosaved config (load with --resume flag)","file":"/config/caddy/autosave.json"}
mercure-1       | {"level":"info","ts":1703174081.6452782,"msg":"serving initial configuration"}
mercure-1       | {"level":"warn","ts":1703174081.6490808,"logger":"tls","msg":"storage cleaning happened too recently; skipping for now","storage":"FileStorage:/data/caddy","instance":"3997bdb3-1b33-493d-bf54-fb4c408489cd","try_again":1703260481.6490772,"try_again_in":86399.999999591}
mercure-1       | {"level":"info","ts":1703174081.6491592,"logger":"tls","msg":"finished cleaning storage units"}
mysql-1         | [Entrypoint] Starting MySQL 8.0.32-1.2.11-server
mysql-1         | 2023-12-21T15:54:41.860104Z 0 [Warning] [MY-011068] [Server] The syntax '--skip-host-cache' is deprecated and will be removed in a future release. Please use SET GLOBAL host_cache_size=0 instead.
mysql-1         | 2023-12-21T15:54:41.861775Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.32) starting as process 1
mysql-1         | 2023-12-21T15:54:41.867903Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
laravel.test-1  | usermod: no changes
mysql-1         | 2023-12-21T15:54:41.998079Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
laravel.test-1  | 2023-12-21 15:54:42,081 INFO Set uid to user 0 succeeded
laravel.test-1  | 2023-12-21 15:54:42,082 INFO supervisord started with pid 1
mysql-1         | 2023-12-21T15:54:42.148201Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
mysql-1         | 2023-12-21T15:54:42.148261Z 0 [System] [MY-013602] [Server] Channel mysql_main configured to support TLS. Encrypted connections are now supported for this channel.
mysql-1         | 2023-12-21T15:54:42.168250Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Bind-address: '::' port: 33060, socket: /var/run/mysqld/mysqlx.sock
mysql-1         | 2023-12-21T15:54:42.168307Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.32'  socket: '/var/lib/mysql/mysql.sock'  port: 3306  MySQL Community Server - GPL.
laravel.test-1  | 2023-12-21 15:54:43,084 INFO spawned: 'php' with pid 8
laravel.test-1  | 2023-12-21 15:54:44,086 INFO success: php entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
laravel.test-1  |
laravel.test-1  |    INFO  Server running on [http://0.0.0.0:80].
laravel.test-1  |
laravel.test-1  |   Press Ctrl+C to stop the server
laravel.test-1  |
mercure-1       | {"level":"info","ts":1703174486.7544103,"logger":"http.handlers.mercure","msg":"New subscriber","subscriber":{"id":"urn:uuid:30722d6b-ab87-4fdc-ab4d-09f1c2995103","last_event_id":"","remote_addr":"172.19.0.1:58780","topic_selectors":["public.{event}","private.2.{event}"],"topics":["public.newMessage"]}}
mercure-1       | {"level":"info","ts":1703174486.7587354,"logger":"http.handlers.mercure","msg":"New subscriber","subscriber":{"id":"urn:uuid:6bbb438a-b257-4b92-9bb5-1844665322b8","last_event_id":"","remote_addr":"172.19.0.1:58790","topic_selectors":["public.{event}","private.2.{event}"],"topics":["private.2.newMessage"]}}
laravel.test-1  |   2023-12-21 16:01:21 ................................................... ~ 5s
laravel.test-1  |   2023-12-21 16:01:26 /build/assets/app-c2b61067.css .................... ~ 0s
laravel.test-1  |   2023-12-21 16:01:26 /build/assets/app-c7657dfc.js ..................... ~ 0s
laravel.test-1  |   2023-12-21 16:01:26 /favicon.ico ...................................... ~ 0s
mercure-1       | {"level":"info","ts":1703174510.3827791,"logger":"http.handlers.mercure","msg":"New subscriber","subscriber":{"id":"urn:uuid:6517742c-4d95-46d0-a58e-777bff6f94c7","last_event_id":"","remote_addr":"172.19.0.1:49214","topic_selectors":["public.{event}","private.2.{event}"],"topics":["public.newMessage"]}}
mercure-1       | {"level":"info","ts":1703174510.3919957,"logger":"http.handlers.mercure","msg":"Subscriber disconnected","subscriber":{"id":"urn:uuid:6bbb438a-b257-4b92-9bb5-1844665322b8","last_event_id":"","remote_addr":"172.19.0.1:58790","topic_selectors":["public.{event}","private.2.{event}"],"topics":["private.2.newMessage"]}}
mercure-1       | 2023/12/21 16:01:50.392       INFO    http.log.access.log0    handled request {"request": {"remote_ip": "172.19.0.1", "remote_port": "58790", "client_ip": "172.19.0.1", "proto": "HTTP/1.1", "method": "GET", "host": "localhost:8888", "uri": "/.well-known/mercure?topic=private.2.newMessage", "headers": {"Cookie": [], "Sec-Ch-Ua-Platform": ["\"Android\""], "Origin": ["http://localhost"], "Sec-Fetch-Site": ["same-site"], "Sec-Fetch-Mode": ["cors"], "Sec-Fetch-Dest": ["empty"], "Sec-Ch-Ua": ["\"Not_A Brand\";v=\"8\", \"Chromium\";v=\"120\", \"Google Chrome\";v=\"120\""], "Cache-Control": ["no-cache"], "Accept": ["text/event-stream"], "Accept-Encoding": ["gzip, deflate, br"], "Accept-Language": ["en-US,en;q=0.9"], "Connection": ["keep-alive"], "Sec-Ch-Ua-Mobile": ["?1"], "User-Agent": ["Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Mobile Safari/537.36"], "Referer": ["http://localhost/"]}}, "bytes_read": 0, "user_id": "", "duration": 23.653105757, "size": 2, "status": 200, "resp_headers": {"Connection": ["keep-alive"], "Expire": ["0"], "Content-Type": ["text/event-stream"], "Cache-Control": ["private, no-cache, no-store, must-revalidate, max-age=0"], "Server": ["Caddy"], "X-Content-Type-Options": ["nosniff"], "X-Xss-Protection": ["1; mode=block"], "Access-Control-Allow-Credentials": ["true"], "Access-Control-Allow-Origin": ["http://localhost"], "Content-Security-Policy": ["default-src 'self' mercure.rocks cdn.jsdelivr.net"], "X-Frame-Options": ["DENY"], "Pragma": ["no-cache"], "X-Accel-Buffering": ["no"]}}
mercure-1       | {"level":"info","ts":1703174510.397029,"logger":"http.handlers.mercure","msg":"Subscriber disconnected","subscriber":{"id":"urn:uuid:30722d6b-ab87-4fdc-ab4d-09f1c2995103","last_event_id":"","remote_addr":"172.19.0.1:58780","topic_selectors":["public.{event}","private.2.{event}"],"topics":["public.newMessage"]}}
mercure-1       | 2023/12/21 16:01:50.397       INFO    http.log.access.log0    handled request {"request": {"remote_ip": "172.19.0.1", "remote_port": "58780", "client_ip": "172.19.0.1", "proto": "HTTP/1.1", "method": "GET", "host": "localhost:8888", "uri": "/.well-known/mercure?topic=public.newMessage", "headers": {"Sec-Ch-Ua-Mobile": ["?1"], "Sec-Ch-Ua-Platform": ["\"Android\""], "Sec-Fetch-Mode": ["cors"], "Accept-Language": ["en-US,en;q=0.9"], "Connection": ["keep-alive"], "Accept": ["text/event-stream"], "Origin": ["http://localhost"], "Referer": ["http://localhost/"], "Cookie": [], "Sec-Ch-Ua": ["\"Not_A Brand\";v=\"8\", \"Chromium\";v=\"120\", \"Google Chrome\";v=\"120\""], "Cache-Control": ["no-cache"], "Sec-Fetch-Site": ["same-site"], "User-Agent": ["Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Mobile Safari/537.36"], "Sec-Fetch-Dest": ["empty"], "Accept-Encoding": ["gzip, deflate, br"]}}, "bytes_read": 0, "user_id": "", "duration": 23.659357655, "size": 2, "status": 200, "resp_headers": {"Server": ["Caddy"], "Access-Control-Allow-Origin": ["http://localhost"], "X-Frame-Options": ["DENY"], "Connection": ["keep-alive"], "Pragma": ["no-cache"], "Expire": ["0"], "X-Content-Type-Options": ["nosniff"], "Content-Security-Policy": ["default-src 'self' mercure.rocks cdn.jsdelivr.net"], "Access-Control-Allow-Credentials": ["true"], "Content-Type": ["text/event-stream"], "X-Xss-Protection": ["1; mode=block"], "Cache-Control": ["private, no-cache, no-store, must-revalidate, max-age=0"], "X-Accel-Buffering": ["no"]}}
mercure-1       | {"level":"info","ts":1703174518.3048244,"logger":"http.handlers.mercure","msg":"Subscriber disconnected","subscriber":{"id":"urn:uuid:6517742c-4d95-46d0-a58e-777bff6f94c7","last_event_id":"","remote_addr":"172.19.0.1:49214","topic_selectors":["public.{event}","private.2.{event}"],"topics":["public.newMessage"]}}
mercure-1       | 2023/12/21 16:01:58.304       INFO    http.log.access.log0    handled request {"request": {"remote_ip": "172.19.0.1", "remote_port": "49214", "client_ip": "172.19.0.1", "proto": "HTTP/1.1", "method": "GET", "host": "localhost:8888", "uri": "/.well-known/mercure?topic=public.newMessage", "headers": {"Upgrade-Insecure-Requests": ["1"], "Sec-Ch-Ua-Platform": ["\"Android\""], "User-Agent": ["Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Mobile Safari/537.36"], "Sec-Fetch-Mode": ["navigate"], "Accept-Encoding": ["gzip, deflate, br"], "Sec-Ch-Ua-Mobile": ["?1"], "Sec-Ch-Ua": ["\"Not_A Brand\";v=\"8\", \"Chromium\";v=\"120\", \"Google Chrome\";v=\"120\""], "Accept": ["text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7"], "Cookie": [], "Sec-Fetch-Site": ["none"], "Sec-Fetch-User": ["?1"], "Sec-Fetch-Dest": ["document"], "Accept-Language": ["en-US,en;q=0.9"], "Connection": ["keep-alive"]}}, "bytes_read": 0, "user_id": "", "duration": 7.935280053, "size": 2, "status": 200, "resp_headers": {"Server": ["Caddy"], "X-Content-Type-Options": ["nosniff"], "Content-Security-Policy": ["default-src 'self' mercure.rocks cdn.jsdelivr.net"], "Content-Type": ["text/event-stream"], "Cache-Control": ["private, no-cache, no-store, must-revalidate, max-age=0"], "X-Xss-Protection": ["1; mode=block"], "X-Frame-Options": ["DENY"], "Connection": ["keep-alive"], "Pragma": ["no-cache"], "Expire": ["0"], "X-Accel-Buffering": ["no"]}}
mercure-1       | {"level":"info","ts":1703174518.3669512,"logger":"http.handlers.mercure","msg":"New subscriber","subscriber":{"id":"urn:uuid:8ff69f06-a8eb-4d39-9dc0-f9e66a0b609f","last_event_id":"","remote_addr":"172.19.0.1:40502","topic_selectors":["public.{event}","private.2.{event}"],"topics":["public.newMessage"]}}
mercure-1       | {"level":"info","ts":1703174518.3701656,"logger":"http.handlers.mercure","msg":"New subscriber","subscriber":{"id":"urn:uuid:b3aa572e-5eab-4146-b8ec-bb6756aa0a16","last_event_id":"","remote_addr":"172.19.0.1:40514","topic_selectors":["public.{event}","private.2.{event}"],"topics":["private.2.newMessage"]}}
laravel.test-1  |   2023-12-21 16:01:56 ................................................... ~ 2s
laravel.test-1  |   2023-12-21 16:01:58 /favicon.ico ...................................... ~ 0s
```

![image](https://github.com/benbjurstrom/livewire-mercure-demo/assets/22586660/c114f0c4-41c4-44c1-9b51-f9ff54f3f921)

**Comment by robindrost** [comment]
Followed the installing step but got the same issue running Sail.

**Comment by hen3b182** [comment]
Ah, too bad, i thought maybe it was me, hopefully someone can help

**Comment by benbjurstrom** [comment]
Looks like it was a docker networking issue. For consistency between environments I added the ability to handle messages sent from inside the container. Pull down the latest changes and try running the command with

```bash
./vendor/bin/sail artisan message:send
```

**Comment by hen3b182** [comment]
i am on docker already, added the MERC URL env, but that didn't fix it. my docker-compose:
```
services:
    laravel.test:
        build:
            context: ./vendor/laravel/sail/runtimes/8.2
            dockerfile: Dockerfile
            args:
                WWWGROUP: '1000'
        image: sail-8.2/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '1000'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
            MERCURE_URL: 'http://mercure/.well-known/mercure'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - mysql
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'sail-mysql:/var/lib/mysql'
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
    mercure:
        image: dunglas/mercure
        restart: unless-stopped
        environment:
            # Uncomment the following line to disable HTTPS
            SERVER_NAME: ':80'
            MERCURE_PUBLISHER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
            MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
            MERCURE_EXTRA_DIRECTIVES: |
                cors_origins http://localhost
                ui
                subscriptions
        # Uncomment the following line to enable the development mode
        command: /usr/bin/caddy run --config /etc/caddy/Caddyfile.dev
        ports:
            - '8888:80'
            - '4433:443'
        volumes:
            - mercure_data:/data
            - mercure_config:/config
networks:
    sail:
        driver: bridge
volumes:
    mercure_data:
    mercure_config:
    sail-mysql:
        driver: local
```

commands:
1. docker compose up
2. docker exec -it a4b7f9ef240f sh
3. php artisan message:send
4. 
![image](https://github.com/benbjurstrom/livewire-mercure-demo/assets/22586660/d48060a9-b5d8-4e4d-b0fd-489220ec83c9)

docker console:
```
time="2023-12-22T01:54:45+01:00" level=warning msg="The \"PWD\" variable is not set. Defaulting to a blank string."
[+] Running 3/3
 ✔ Container livewire-mercure-demo-mysql-1         Created                                                                                    0.0s
 ✔ Container livewire-mercure-demo-mercure-1       Created                                                                                    0.0s
 ✔ Container livewire-mercure-demo-laravel.test-1  Recreated                                                                                  0.3s
Attaching to laravel.test-1, mercure-1, mysql-1
mysql-1         | [Entrypoint] MySQL Docker Image 8.0.32-1.2.11-server
mercure-1       | {"level":"info","ts":1703206486.4119763,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile.dev","config_adapter":""}
mercure-1       | {"level":"warn","ts":1703206486.413984,"msg":"Caddyfile input is not formatted; run 'caddy fmt --overwrite' to fix inconsistencies","adapter":"caddyfile","file":"/etc/caddy/Caddyfile.dev","line":3}
mysql-1         | [Entrypoint] Starting MySQL 8.0.32-1.2.11-server
mercure-1       | {"level":"info","ts":1703206486.416216,"logger":"admin","msg":"admin endpoint started","address":"localhost:2019","enforce_origin":false,"origins":["//127.0.0.1:2019","//localhost:2019","//[::1]:2019"]}
mercure-1       | {"level":"warn","ts":1703206486.4165163,"logger":"http.auto_https","msg":"server is listening only on the HTTP port, so no automatic HTTPS will be applied to this server","server_name":"srv0","http_port":80}
mercure-1       | {"level":"info","ts":1703206486.4166293,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0xc0004a5680"}
mercure-1       | {"level":"info","ts":1703206486.4172907,"logger":"http.log","msg":"server running","name":"srv0","protocols":["h1","h2","h3"]}
mercure-1       | {"level":"info","ts":1703206486.4174254,"msg":"autosaved config (load with --resume flag)","file":"/config/caddy/autosave.json"}
mercure-1       | {"level":"info","ts":1703206486.4174416,"msg":"serving initial configuration"}
mercure-1       | {"level":"warn","ts":1703206486.441634,"logger":"tls","msg":"storage cleaning happened too recently; skipping for now","storage":"FileStorage:/data/caddy","instance":"3997bdb3-1b33-493d-bf54-fb4c408489cd","try_again":1703292886.441631,"try_again_in":86399.999999433}
mercure-1       | {"level":"info","ts":1703206486.4417179,"logger":"tls","msg":"finished cleaning storage units"}
mysql-1         | 2023-12-22T00:54:46.863526Z 0 [Warning] [MY-011068] [Server] The syntax '--skip-host-cache' is deprecated and will be removed in a future release. Please use SET GLOBAL host_cache_size=0 instead.
mysql-1         | 2023-12-22T00:54:46.864459Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.32) starting as process 1
mysql-1         | 2023-12-22T00:54:46.900290Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
mysql-1         | 2023-12-22T00:54:47.217272Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
laravel.test-1  | 2023-12-22 00:54:47,232 INFO Set uid to user 0 succeeded
laravel.test-1  | 2023-12-22 00:54:47,233 INFO supervisord started with pid 1
mysql-1         | 2023-12-22T00:54:47.697987Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
mysql-1         | 2023-12-22T00:54:47.698029Z 0 [System] [MY-013602] [Server] Channel mysql_main configured to support TLS. Encrypted connections are now supported for this channel.
mysql-1         | 2023-12-22T00:54:47.724033Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Bind-address: '::' port: 33060, socket: /var/run/mysqld/mysqlx.sock
mysql-1         | 2023-12-22T00:54:47.724077Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.32'  socket: '/var/lib/mysql/mysql.sock'  port: 3306  MySQL Community Server - GPL.
laravel.test-1  | 2023-12-22 00:54:48,236 INFO spawned: 'php' with pid 16
mercure-1       | {"level":"info","ts":1703206488.391924,"logger":"http.handlers.mercure","msg":"New subscriber","subscriber":{"id":"urn:uuid:0baacb83-ee03-455a-8c00-43e64fcf12ea","last_event_id":"","remote_addr":"172.19.0.1:39548","topics":["private.2.newMessage"]}}
mercure-1       | {"level":"info","ts":1703206488.39614,"logger":"http.handlers.mercure","msg":"New subscriber","subscriber":{"id":"urn:uuid:07719637-80ae-4510-b1c2-f6f1842c7584","last_event_id":"","remote_addr":"172.19.0.1:39558","topics":["public.newMessage"]}}
laravel.test-1  | 2023-12-22 00:54:49,237 INFO success: php entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
laravel.test-1  |
laravel.test-1  |    INFO  Server running on [http://0.0.0.0:80].
laravel.test-1  |
laravel.test-1  |   Press Ctrl+C to stop the server
laravel.test-1  |
laravel.test-1  |   2023-12-22 00:55:13 ................................................... ~ 4s
mercure-1       | {"level":"info","ts":1703206520.2626755,"logger":"http.handlers.mercure","msg":"Subscriber disconnected","subscriber":{"id":"urn:uuid:0baacb83-ee03-455a-8c00-43e64fcf12ea","last_event_id":"","remote_addr":"172.19.0.1:39548","topics":["private.2.newMessage"]}}
mercure-1       | 2023/12/22 00:55:20.262       INFO    http.log.access.log0    handled request {"request": {"remote_ip": "172.19.0.1", "remote_port": "39548", "client_ip": "172.19.0.1", "proto": "HTTP/1.1", "method": "GET", "host": "localhost:8888", "uri": "/.well-known/mercure?topic=private.2.newMessage", "headers": {"Sec-Ch-Ua-Mobile": ["?1"], "User-Agent": ["Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Mobile Safari/537.36"], "Origin": ["http://localhost"], "Accept-Language": ["en-US,en;q=0.9"], "Connection": ["keep-alive"], "Sec-Ch-Ua": ["\"Not_A Brand\";v=\"8\", \"Chromium\";v=\"120\", \"Google Chrome\";v=\"120\""], "Sec-Fetch-Site": ["same-site"], "Sec-Fetch-Mode": ["cors"], "Sec-Fetch-Dest": ["empty"], "Accept-Encoding": ["gzip, deflate, br"], "Accept": ["text/event-stream"], "Sec-Ch-Ua-Platform": ["\"Android\""], "Referer": ["http://localhost/"], "Cache-Control": ["no-cache"]}}, "bytes_read": 0, "user_id": "", "duration": 31.879171818, "size": 2, "status": 200, "resp_headers": {"Server": ["Caddy"], "Connection": ["keep-alive"], "Expire": ["0"], "X-Content-Type-Options": ["nosniff"], "Access-Control-Allow-Origin": ["http://localhost"], "X-Frame-Options": ["DENY"], "Content-Security-Policy": ["default-src 'self' mercure.rocks cdn.jsdelivr.net"], "Content-Type": ["text/event-stream"], "Pragma": ["no-cache"], "X-Accel-Buffering": ["no"], "X-Xss-Protection": ["1; mode=block"], "Access-Control-Allow-Credentials": ["true"], "Cache-Control": ["private, no-cache, no-store, must-revalidate, max-age=0"]}}
mercure-1       | {"level":"info","ts":1703206520.2681463,"logger":"http.handlers.mercure","msg":"Subscriber disconnected","subscriber":{"id":"urn:uuid:07719637-80ae-4510-b1c2-f6f1842c7584","last_event_id":"","remote_addr":"172.19.0.1:39558","topics":["public.newMessage"]}}
mercure-1       | 2023/12/22 00:55:20.268       INFO    http.log.access.log0    handled request {"request": {"remote_ip": "172.19.0.1", "remote_port": "39558", "client_ip": "172.19.0.1", "proto": "HTTP/1.1", "method": "GET", "host": "localhost:8888", "uri": "/.well-known/mercure?topic=public.newMessage", "headers": {"Sec-Ch-Ua": ["\"Not_A Brand\";v=\"8\", \"Chromium\";v=\"120\", \"Google Chrome\";v=\"120\""], "Sec-Fetch-Mode": ["cors"], "User-Agent": ["Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Mobile Safari/537.36"], "Accept-Encoding": ["gzip, deflate, br"], "Accept-Language": ["en-US,en;q=0.9"], "Connection": ["keep-alive"], "Accept": ["text/event-stream"], "Cache-Control": ["no-cache"], "Sec-Ch-Ua-Mobile": ["?1"], "Sec-Ch-Ua-Platform": ["\"Android\""], "Origin": ["http://localhost"], "Sec-Fetch-Site": ["same-site"], "Sec-Fetch-Dest": ["empty"], "Referer": ["http://localhost/"]}}, "bytes_read": 0, "user_id": "", "duration": 31.884627515, "size": 2, "status": 200, "resp_headers": {"Pragma": ["no-cache"], "X-Accel-Buffering": ["no"], "Content-Security-Policy": ["default-src 'self' mercure.rocks cdn.jsdelivr.net"], "Access-Control-Allow-Credentials": ["true"], "Content-Type": ["text/event-stream"], "Cache-Control": ["private, no-cache, no-store, must-revalidate, max-age=0"], "Server": ["Caddy"], "X-Content-Type-Options": ["nosniff"], "Connection": ["keep-alive"], "X-Xss-Protection": ["1; mode=block"], "Access-Control-Allow-Origin": ["http://localhost"], "X-Frame-Options": ["DENY"], "Expire": ["0"]}}
laravel.test-1  |   2023-12-22 00:55:17 ................................................... ~ 3s
laravel.test-1  |   2023-12-22 00:55:20 /build/assets/app-c2b61067.css .................... ~ 0s
laravel.test-1  |   2023-12-22 00:55:20 ................................................... ~ 2s
laravel.test-1  |   2023-12-22 00:55:20 /build/assets/app-c7657dfc.js ..................... ~ 2s
laravel.test-1  |   2023-12-22 00:55:22 /favicon.ico ...................................... ~ 0s
laravel.test-1  |   2023-12-22 00:55:26 ................................................... ~ 2s
laravel.test-1  |   2023-12-22 00:55:28 ................................................... ~ 1s
laravel.test-1  |   2023-12-22 00:55:29 ................................................... ~ 0s
laravel.test-1  |   2023-12-22 00:55:29 /build/assets/app-c2b61067.css .................... ~ 0s
laravel.test-1  |   2023-12-22 00:55:29 /build/assets/app-c7657dfc.js ..................... ~ 0s
laravel.test-1  |   2023-12-22 00:55:29 /favicon.ico ...................................... ~ 0s
laravel.test-1  |   2023-12-22 00:55:38 ................................................... ~ 3s
mercure-1       | {"level":"info","ts":1703206547.2384622,"logger":"http.handlers.mercure","msg":"New subscriber","subscriber":{"id":"urn:uuid:8f0046cb-d473-4742-a4d3-dc9eee67923b","last_event_id":"","remote_addr":"172.19.0.1:38242","topic_selectors":["public.{event}","private.1.{event}"],"topics":["private.1.newMessage"]}}
mercure-1       | {"level":"info","ts":1703206547.241894,"logger":"http.handlers.mercure","msg":"New subscriber","subscriber":{"id":"urn:uuid:60311423-b51a-4691-ae02-fdf990203dfc","last_event_id":"","remote_addr":"172.19.0.1:38250","topic_selectors":["public.{event}","private.1.{event}"],"topics":["public.newMessage"]}}
laravel.test-1  |   2023-12-22 00:55:41 ................................................... ~ 6s
laravel.test-1  |   2023-12-22 00:55:47 /build/assets/app-c2b61067.css .................... ~ 0s
laravel.test-1  |   2023-12-22 00:55:47 /favicon.ico ...................................... ~ 0s
laravel.test-1  |   2023-12-22 00:55:48 ................................................... ~ 2s
mercure-1       | {"level":"info","ts":1703206551.386636,"logger":"http.handlers.mercure","msg":"New subscriber","subscriber":{"id":"urn:uuid:7a5083c2-565e-452a-8d4c-acac9d7975c3","last_event_id":"","remote_addr":"172.19.0.1:38254","topic_selectors":["public.{event}","private.2.{event}"],"topics":["public.newMessage"]}}
mercure-1       | {"level":"info","ts":1703206551.390176,"logger":"http.handlers.mercure","msg":"New subscriber","subscriber":{"id":"urn:uuid:91539ec7-7db8-42ef-b05e-0c94edf7cf35","last_event_id":"","remote_addr":"172.19.0.1:38262","topic_selectors":["public.{event}","private.2.{event}"],"topics":["private.2.newMessage"]}}
laravel.test-1  |   2023-12-22 00:55:50 ................................................... ~ 1s
laravel.test-1  |   2023-12-22 00:55:51 /build/assets/app-c2b61067.css .................... ~ 0s
laravel.test-1  |   2023-12-22 00:55:51 /favicon.ico ...................................... ~ 0s
```

**Comment by benbjurstrom** [comment]
@hen3b182 you also have to add the mercure container to the sail network

```yml
    mercure:
        image: dunglas/mercure
        networks:
            - sail
        ...
```
